.globl accumulatorone
.globl accumulatortwo
.globl accumulatorthree
.globl accumulatorfour
.globl accumulatorfive

#Accumulator:
#Inputs: a0 contains a pointer to an array of nonzero integers, terminated with 0
#Output: a0 should return the sum of the elements of the array
#
#Example: Let a0 = [1,2,3,4,5,6,7,0]
#
#         Then the expected output (in a0) is 1+2+3+4+5+6+7=28

#DO NOT EDIT THIS FILE
#We have provided five versions of accumulator. Only one is correct, though all five pass the sanity test above.

accumulatorone:
	addi sp sp -12
	sw s0 0(sp)
    sw s1, 4(sp)
	sw ra 8(sp)
    
	li s0, 0
    add s1, a0, x0


Loopone:
    lw t0, 0(s1)
    beq t0 x0 Endone
    add s0 ,s0, t0
	addi s1 s1 4
	jal Loopone
    

Endone:
	add a0, s0, x0
	lw s0 0(sp)
    lw s1, 4(sp)
	lw ra 8(sp)
	addi sp sp 12
	jr ra

accumulatortwo:
	# revision
	addi sp sp -4
	sw s0 0(sp)
	li t0 0
	li s0 0
Looptwo:
	slli t1 t0 2
	add t2 a0 t1
	lw t3 0(t2)
	add s0 s0 t3
	addi t0 t0 1
	bnez t3 Looptwo
	j Endtwo
Endtwo:
	mv a0 s0
	lw s0 0(sp)
	addi sp sp 4
	jr ra

accumulatorthree:
	addi sp sp -8
	sw s0 0(sp)
	sw ra 4(sp)
	lw s0 0(a0)
	beq s0 x0 TailCasethree
	addi a0 a0 4
	jal accumulatorthree
	add a0 a0 s0
	j Epiloguethree
TailCasethree:
	mv a0 x0
	j Epiloguethree
Epiloguethree:	
	lw s0 0(sp)
	lw ra 4(sp)
	addi sp sp 8
	jr ra

accumulatorfour:
    li t2, 0
Loopfour:
	lw t1 0(a0)
    # revision
	beq t1 x0 Endfour
	add t2 t2 t1
	addi a0 a0 4
	j Loopfour
Endfour:
	mv a0 t2
	jr ra

accumulatorfive:
	addi sp sp -8
	sw s0 0(sp)
	sw ra 4(sp)
	mv s0 a0
	lw a0 0(a0)
	beq a0, x0, Endfive
Loopfive:
	addi s0 s0 4
	lw t0 0(s0)
	add a0 a0 t0
	bne t0 x0 Loopfive
Endfive:
	lw s0 0(sp)
	lw ra 4(sp)
	addi sp sp 8
	jr ra


	